/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as PullRequestsRouteImport } from './routes/pull-requests'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PairRouteImport } from './routes/pair'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsWorkersRouteImport } from './routes/settings.workers'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsProjectsRouteImport } from './routes/settings.projects'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsJarvisRouteImport } from './routes/settings.jarvis'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsCapabilitiesRouteImport } from './routes/settings.capabilities'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ProjectsManageRouteImport } from './routes/projects_.manage'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as ChatJarvisProjectEnvironmentIdProjectIdRouteImport } from './routes/_chat.jarvis-project.$environmentId.$projectId'
import { Route as ChatJarvisProjectEnvironmentIdProjectIdThreadIdRouteImport } from './routes/_chat.jarvis-project.$environmentId.$projectId.$threadId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const PullRequestsRoute = PullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsWorkersRoute = SettingsWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsJarvisRoute = SettingsJarvisRouteImport.update({
  id: '/jarvis',
  path: '/jarvis',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCapabilitiesRoute = SettingsCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsManageRoute = ProjectsManageRouteImport.update({
  id: '/projects_/manage',
  path: '/projects/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatJarvisProjectEnvironmentIdProjectIdRoute =
  ChatJarvisProjectEnvironmentIdProjectIdRouteImport.update({
    id: '/jarvis-project/$environmentId/$projectId',
    path: '/jarvis-project/$environmentId/$projectId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatJarvisProjectEnvironmentIdProjectIdThreadIdRoute =
  ChatJarvisProjectEnvironmentIdProjectIdThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => ChatJarvisProjectEnvironmentIdProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/projects': typeof ProjectsRoute
  '/pull-requests': typeof PullRequestsRoute
  '/routines': typeof RoutinesRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRouteWithChildren
  '/projects/manage': typeof ProjectsManageRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/capabilities': typeof SettingsCapabilitiesRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/jarvis': typeof SettingsJarvisRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/workers': typeof SettingsWorkersRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/jarvis-project/$environmentId/$projectId': typeof ChatJarvisProjectEnvironmentIdProjectIdRouteWithChildren
  '/jarvis-project/$environmentId/$projectId/$threadId': typeof ChatJarvisProjectEnvironmentIdProjectIdThreadIdRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/projects': typeof ProjectsRoute
  '/pull-requests': typeof PullRequestsRoute
  '/routines': typeof RoutinesRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRouteWithChildren
  '/projects/manage': typeof ProjectsManageRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/capabilities': typeof SettingsCapabilitiesRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/jarvis': typeof SettingsJarvisRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/workers': typeof SettingsWorkersRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/jarvis-project/$environmentId/$projectId': typeof ChatJarvisProjectEnvironmentIdProjectIdRouteWithChildren
  '/jarvis-project/$environmentId/$projectId/$threadId': typeof ChatJarvisProjectEnvironmentIdProjectIdThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/projects': typeof ProjectsRoute
  '/pull-requests': typeof PullRequestsRoute
  '/routines': typeof RoutinesRoute
  '/scheduled': typeof ScheduledRoute
  '/settings': typeof SettingsRouteWithChildren
  '/projects_/manage': typeof ProjectsManageRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/capabilities': typeof SettingsCapabilitiesRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/jarvis': typeof SettingsJarvisRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/workers': typeof SettingsWorkersRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_chat/jarvis-project/$environmentId/$projectId': typeof ChatJarvisProjectEnvironmentIdProjectIdRouteWithChildren
  '/_chat/jarvis-project/$environmentId/$projectId/$threadId': typeof ChatJarvisProjectEnvironmentIdProjectIdThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/projects'
    | '/pull-requests'
    | '/routines'
    | '/scheduled'
    | '/settings'
    | '/projects/manage'
    | '/settings/archived'
    | '/settings/capabilities'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/jarvis'
    | '/settings/keybindings'
    | '/settings/mcp'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/source-control'
    | '/settings/workers'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/jarvis-project/$environmentId/$projectId'
    | '/jarvis-project/$environmentId/$projectId/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/projects'
    | '/pull-requests'
    | '/routines'
    | '/scheduled'
    | '/settings'
    | '/projects/manage'
    | '/settings/archived'
    | '/settings/capabilities'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/jarvis'
    | '/settings/keybindings'
    | '/settings/mcp'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/source-control'
    | '/settings/workers'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/jarvis-project/$environmentId/$projectId'
    | '/jarvis-project/$environmentId/$projectId/$threadId'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/projects'
    | '/pull-requests'
    | '/routines'
    | '/scheduled'
    | '/settings'
    | '/projects_/manage'
    | '/settings/archived'
    | '/settings/capabilities'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/jarvis'
    | '/settings/keybindings'
    | '/settings/mcp'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/source-control'
    | '/settings/workers'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/_chat/jarvis-project/$environmentId/$projectId'
    | '/_chat/jarvis-project/$environmentId/$projectId/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  ProjectsRoute: typeof ProjectsRoute
  PullRequestsRoute: typeof PullRequestsRoute
  RoutinesRoute: typeof RoutinesRoute
  ScheduledRoute: typeof ScheduledRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ProjectsManageRoute: typeof ProjectsManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pull-requests': {
      id: '/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof PullRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/workers': {
      id: '/settings/workers'
      path: '/workers'
      fullPath: '/settings/workers'
      preLoaderRoute: typeof SettingsWorkersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/jarvis': {
      id: '/settings/jarvis'
      path: '/jarvis'
      fullPath: '/settings/jarvis'
      preLoaderRoute: typeof SettingsJarvisRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/capabilities': {
      id: '/settings/capabilities'
      path: '/capabilities'
      fullPath: '/settings/capabilities'
      preLoaderRoute: typeof SettingsCapabilitiesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects_/manage': {
      id: '/projects_/manage'
      path: '/projects/manage'
      fullPath: '/projects/manage'
      preLoaderRoute: typeof ProjectsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/jarvis-project/$environmentId/$projectId': {
      id: '/_chat/jarvis-project/$environmentId/$projectId'
      path: '/jarvis-project/$environmentId/$projectId'
      fullPath: '/jarvis-project/$environmentId/$projectId'
      preLoaderRoute: typeof ChatJarvisProjectEnvironmentIdProjectIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/jarvis-project/$environmentId/$projectId/$threadId': {
      id: '/_chat/jarvis-project/$environmentId/$projectId/$threadId'
      path: '/$threadId'
      fullPath: '/jarvis-project/$environmentId/$projectId/$threadId'
      preLoaderRoute: typeof ChatJarvisProjectEnvironmentIdProjectIdThreadIdRouteImport
      parentRoute: typeof ChatJarvisProjectEnvironmentIdProjectIdRoute
    }
  }
}

interface ChatJarvisProjectEnvironmentIdProjectIdRouteChildren {
  ChatJarvisProjectEnvironmentIdProjectIdThreadIdRoute: typeof ChatJarvisProjectEnvironmentIdProjectIdThreadIdRoute
}

const ChatJarvisProjectEnvironmentIdProjectIdRouteChildren: ChatJarvisProjectEnvironmentIdProjectIdRouteChildren =
  {
    ChatJarvisProjectEnvironmentIdProjectIdThreadIdRoute:
      ChatJarvisProjectEnvironmentIdProjectIdThreadIdRoute,
  }

const ChatJarvisProjectEnvironmentIdProjectIdRouteWithChildren =
  ChatJarvisProjectEnvironmentIdProjectIdRoute._addFileChildren(
    ChatJarvisProjectEnvironmentIdProjectIdRouteChildren,
  )

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
  ChatJarvisProjectEnvironmentIdProjectIdRoute: typeof ChatJarvisProjectEnvironmentIdProjectIdRouteWithChildren
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
  ChatJarvisProjectEnvironmentIdProjectIdRoute:
    ChatJarvisProjectEnvironmentIdProjectIdRouteWithChildren,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsCapabilitiesRoute: typeof SettingsCapabilitiesRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsJarvisRoute: typeof SettingsJarvisRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsWorkersRoute: typeof SettingsWorkersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsCapabilitiesRoute: SettingsCapabilitiesRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsJarvisRoute: SettingsJarvisRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsWorkersRoute: SettingsWorkersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  ProjectsRoute: ProjectsRoute,
  PullRequestsRoute: PullRequestsRoute,
  RoutinesRoute: RoutinesRoute,
  ScheduledRoute: ScheduledRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ProjectsManageRoute: ProjectsManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
